config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
  resources :books, only: [:new, :create, :index, :show, :destroy, :edit, :update] do
    resource :favorites, only: [:create, :destroy]
    resource :book_comments, only: [:create, :destroy]
  end

  resources :users, only:[:show, :edit, :update, :index,] do
    resource :relationships, only: [:create, :destroy]
  end

  get 'users/:id/follow' => 'users#follows',as:'users_follow'
  get 'users/:id/follower' => 'users#followers',as:'users_follower'

  get 'home/about', to: 'homes#show'

  get 'books/:id/edit' => 'books#edit'
  post 'books/:id/edit' => 'books#edit'

  post 'users/:id' => 'books#create'
  post 'users' => 'books#create'
  post 'books/:id' => 'books#create'

  get 'users/:id/edit' => 'users#edit'
  patch 'users/:id' => 'users#update'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user


  has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  has_many :book_comments, dependent: :destroy
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

end

app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates :comment, presence: true

end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book

end

app/models/relationship.rb
class Relationship < ApplicationRecord

  # belongs_to :user
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

  # has_many :followers, :through => :passive_relationships, source: :user

  validates :followed_id, presence: true
  validates :follower_id, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  attachment :profile_image
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :active_relationships, class_name: "Relationship", foreign_key: :followed_id, dependent: :destroy
  has_many :followings, through: :active_relationships, source: :follower
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id, dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :followed

  def followed_by?(user)
    passive_relationships.find_by(followed_id: user.id).present?
  end


  validates :name, presence: true, uniqueness: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top]

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
    redirect_to book_path(book)
  end

  def destroy
    comment = BookComment.find(params[:book_id])
    book = comment.book
    comment.destroy
    redirect_to book_path(book)
    # BookComment.find_by(id: params[:id], book_id: params[book_id]).destroy
    # redirect_back(fallback_location: books_path)
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:create] = "Book was successfully created."
      redirect_to book_path(@book)
    else
      @books = Book.all
      render :index
    end
  end

  def index
    @book = Book.new
    @books = Book.all
  end

  def show
    @book_new = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render :edit
    else
      @books = Book.all
      redirect_to "/books"
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:update] = "Book was successfully updated."
      redirect_to book_path(@book)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :user_id)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_back fallback_location: @book
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_back fallback_location: @book
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
before_action :authenticate_user!,except: [:top, :show]

  def top
  end

  def show
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :authenticate_user!

  def create
    follow = current_user.active_relationships.build(follower_id: params[:user_id])
    follow.save
    redirect_to request.referer
  end

  def destroy
    follow = current_user.active_relationships.find_by(follower_id: params[:user_id])
    follow.destroy
    redirect_to request.referer
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :correct_user, only: [:edit, :update]

  def index
    @users = User.page(params[:page]).reverse_order
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books.page(params[:page]).reverse_order
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    # if @user == current_user
      render "edit"
    # else
    #   redirect_to user_path(current_user.id)
    # end
    #beforeで制限したため、editのif部分は不要
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:update] = "User infomation was successfully updated."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  def follows
    user = User.find(params[:id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:id])
    @users = user.followers
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def correct_user
    user = User.find(params[:id])
    if current_user != user
      redirect_to user_path(current_user.id)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<!--<% books.each do |book| %>-->
<!--<tbody>-->
<!--  <tr>-->
<!--    <td>-->
<!--      <%= link_to user_path(book.user.id), target: "_blank" do %>-->
<!--        <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg" %>-->
<!--      <% end %>-->
<!--    </td>-->

<!--    <td>-->
<!--      <%= link_to book_path(book.id), target: "_blank" do %>-->
<!--        <%=book.title %>-->
<!--      <% end %>-->
<!--    </td>-->

<!--    <td><%= book.body %></td>-->
<!--  </tr>-->
<!--</tbody>-->

<!--<% end %>-->
<!--<%= paginate books %>-->

<!--<%= render 'books/list', books: @books %>-->

app/views/books/edit.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>件のerrorが発生しました
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<p id="notice"></p>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>

        <%= form_with model: @book, local:true do |f| %>
          <div class="form-group">
            <label for="book_title">Title</label>
            <%= f.text_field :title, :class => 'form-control book_title' %>
          </div>

          <div class="form-group">
            <label for="book_opinion">Opinion</label>
            <%= f.text_field :body, :class => 'form-control book_body' %>
          </div>

          <div class="form-group">
            <%= f.submit 'Update Book', class: "btn btn-success"  %>
          </div>


          <%= link_to "Show", @book %>
          |
          <a href="/books">Back</a>
        <% end %>

    </div>
  </div>
</div>

app/views/books/index.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>件のerrorが発生しました
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>


<p id="notice"></p>
<div class="container px-5 px-sm-8">
  <div class="row">

    <%= render 'users/sideBar', users: @users %>

    <div class="col-md-8 offset-md-1">
    <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <% @books.each do |book| %>
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(book.user.id) do %>
                <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size:'40x40' %>
              <% end %>
            </td>

            <td>
              <%= link_to book_path(book) do %>
                <%=book.title %>
              <% end %>
            </td>

            <td><%= book.body %></td>

            <td>
              <% if book.favorited_by?(current_user) %>
                <p>
                  <%= link_to book_favorites_path(book), method: :delete do %>
                    ♥<%= book.favorites.count %>
                  <% end %>
                </p>
                <% else %>
                <p>
                  <%= link_to book_favorites_path(book), method: :post do %>
                    ♡<%= book.favorites.count %>
                  <% end %>
                </p>
              <% end %>
            </td>

          </tr>
        </tbody>

        <% end %>

      </table>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<!--<h1>New Book</h1>-->

<!--<% if @book.errors.any? %>-->
<!--  <%= @book.errors.count %>件のエラーが発生しました-->
<!--  <% @book.errors.full_messages.each do |message| %>-->
<!--    <%= message %>-->
<!--  <% end %>-->
<!--<% end %>-->


<!--<%= form_with model: @book, local:true do |f| %>-->
<!--  <h4>Title</h4>-->
<!--  <%= f.text_field :title %>-->
<!--  <h4>Opinion</h4>-->
<!--  <%= f.text_field :body %>-->
<!--  <%= f.submit '投稿' %>-->
<!--<% end %>-->

app/views/books/show.html.erb
<p id="notice"></p>
<div class="container px-5 px-sm-8">
  <div class="row">

    <div class="col-md-3">

      <h2>User info</h2>
      <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
      <table class="table">
        <tbody>
          <tr>
            <th>name</th>
            <th><%= @user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= @user.introduction %></th>
          </tr>
        </tbody>
      </table>

      <div class="row">
        <%= link_to '', edit_user_path(@user.id), class: 'btn btn-outline-secondary btn-block fas fa-user-cog' %>
      </div>

      <h2 class="mt-3 new_book_title">New book</h2>

      <%= form_with model: @book_new, local:true do |f| %>

        <h4 class="book_title">Title</h4>
        <%= f.text_area :title, size: "20x1" %>
        <h4 class="book_body">Opinion</h4>
        <%= f.text_area :body, size: "20x3" %>
        <div class="form-group">
          <%= f.submit 'Create Book', class: 'btn btn-sm btn-success opinion_field' %>
        </div>
      <% end %>

    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table table-hover table-inverse">

        <tbody class="books-tbody">
          <tr>
            <td>
              <%= link_to user_path(@user.id) do %>
                <%= attachment_image_tag @book.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size:'40x40' %></br>
                <%= @book.user.name %>
              <% end %>
            </td>
            <td>
              <%= link_to book_path(@book.id) do %>
                <%= @book.title %>
              <% end %>
            </td>
            <td><%= @book.body %></td>

            <td>
              <% if @book.favorited_by?(current_user) %>
                <p>
                  <%= link_to book_favorites_path(@book), method: :delete do %>
                    ♥<%= @book.favorites.count %>
                  <% end %>
                </p>
                <% else %>
                <p>
                  <%= link_to book_favorites_path(@book), method: :post do %>
                    ♡<%= @book.favorites.count %>
                  <% end %>
                </p>
              <% end %>
            </td>

            <td>comments：<%= @book.book_comments.count %></td>

            <% if @book.user == current_user %>
              <td><%= link_to "Edit", edit_book_path(@book), class: 'btn btn-sm btn-success' %></td>
              <td><%= link_to "Destroy", book_path(@book), class: 'btn btn-sm btn-danger', method: :delete, data: { confirm: '削除しますか？' } %></td>
            <% end %>

        </tbody>
      </table>

      <h4>Comment</h4>
        <table class="table table-hover table-inverse">
          <tbody>
            <% @book.book_comments.each do |book_comment| %>
            <tr>
              <td>
                <%= attachment_image_tag book_comment.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size:'40x40' %></br>
                <%= link_to @user.name ,user_path(@user.id) %>
              </td>
              <td><%= book_comment.comment %></td>
              <td>
                <% if book_comment.user == current_user %>
                  <%= link_to "Destroy", book_book_comments_path(book_comment), method: :delete, class: "btn btn-danger" %>
                <% end %>
              </td>

            </tr>
            <% end %>
          </tbody>
        </table>

      <div class="row">
        <div class="col-sm-12">
          <%= form_with(model:[@book, @book_comment], local: true) do |f| %>
          <%= f.text_area :comment, rows:'2', class: "form-control", placeholder: "comment" %>
          <div style="margin-top: 20px">
            <%= f.submit "Create Comment" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/homes/show.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i>Bookers!!</h1>
  </div>
</div>

app/views/homes/top.html.erb
<p id="not"></p>
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>Welcome to <i class="fas fa-book"></i>Bookers!!</h1>
      <p>In <i class="fas fa-book"></i>Bookers,</p>
      <p>you can share and exchange your opinions , inpressions , and emotions</br>about various books!</p>

      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
        </div>
        <div class="row">
          <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign Up</a>
        </div>
      </div>


    </div>
  </div>
</div>

app/views/layouts/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!--<link rel="stylesheet" href="../homes../assets/stylesheets/homes.scss">-->

  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">

          <a class="navbar-brand" href="/"><span>Bookers</span></a>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">

              <% if user_signed_in? %>

              <li class="nav-item">
                <%= link_to ' Home', user_path(current_user.id), class: 'fas fa-home nav-link text-light' %>
              </li>
              <li class="nav-item">
                <%= link_to ' Users', users_path, class: 'fas fa-users nav-link text-light' %>
              </li>
              <li class="nav-item">
                <%= link_to ' Books', books_path, class: 'fas fa-book-open nav-link text-light' %>
              </li>
              <li class="nav-item">
                <%= link_to " logout", destroy_user_session_path, method: :delete, class: 'fas fa-sign-out-alt nav-link text-light' %>
              </li>


              <% else %>

              <li class="nav-item">
                <%= link_to " Home", root_path, class: 'fas fa-home  nav-link text-light' %>
              </li>
              <li class="nav-item">
                <%= link_to " About", "/home/about", class: 'fas fa-link nav-link text-light' %>
              </li>
              <li class="nav-item">
                <%= link_to " sign up", new_user_registration_path, class: 'fas fa-user-plus nav-link text-light' %>
              </li>
              <li class="nav-item">
                <%= link_to " login", new_user_session_path, class: 'fas fa-sign-in-alt nav-link text-light' %>
              </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main>
      <%= render 'layouts/flash_message' %>
    <%= yield %>
    </main>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight XXX.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/_sideBar.html.erb
<div class="col-md-3">
  <h2>User info</h2>
  <%= attachment_image_tag current_user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
  <table class="table">
    <tbody>
      <tr>
        <th>name</th>
        <th><%= current_user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= current_user.introduction %></th>
      </tr>
      <tr>
        <th>follows</th>
        <th><%= current_user.followings.count %></th>
      </tr>
      <tr>
        <th>followers</th>
        <th><%= current_user.followers.count %></th>
      </tr>
    </tbody>
  </table>

  <div class="row">
    <%= link_to '', edit_user_path(current_user.id), class: 'btn btn-outline-secondary btn-block fas fa-user-cog' %>
  </div>

  <h2 class="mt-3 new_book_title">New book</h2>

  <%= form_with model: @book, local:true do |f| %>

    <h4 class="book_title">Title</h4>
    <%= f.text_area :title, size: "20x1" %>
    <h4 class="book_body">Opinion</h4>
    <%= f.text_area :body, size: "20x3" %>
    <div class="form-group">
      <%= f.submit 'Create Book', class: 'btn btn-sm btn-success opinion_field' %>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <%= @user.errors.count %>件のerrorが発生しました
  <% @user.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>


<% if @user == current_user %>
  <p id="notice"></p>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h2>User info</h2>

        <%= form_with model:@user, local:true do |f| %>

          <div class="form-group">
            <label for="user_name">Name</label>
            <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前", class: "form-control name" %>
          </div>

          <div class="form-group">
            <label for="user_image">Image</label>
            <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "form-control-file user_image" %>
          </div>

          <div class="form-group">
            <label for="user_introduction">Introduction</label>
            <%= f.text_field :introduction, autofocus: true, id:"inputName", placeholder:"Introduction", class: "form-control introduction" %>
          </div>

          <div class="form-group">
            <%= f.submit "Update User", class: "btn btn-success" %>
          </div>

        <% end %>
      </div>
    </div>
  </div>
<% end %>

<% if @user != current_user %>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <p></p>
      <h2>アクセス権限がありません。</h2>
      </div>
    </div>
  </div>
<% end %>

app/views/users/followers.html.erb
<h1>Follower Users</h1>

<div class="col-xs-9">
  <table class="table">
    <thead>
      <tr>
        <th>image</th>
        <th>name</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= attachment_image_tag user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size:'40x40' %></td>
          <td><%= user.name %></td>
          <td>フォロー数:<%= user.followings.count %></td>
          <td>フォロワー数:<%= user.followers.count %></td>
          <td><%= link_to "Show", user_path(user), class: "user_#{user.id}" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/follows.html.erb
<h1>Follow Users</h1>

<div class="col-xs-9">
  <table class="table">
    <thead>
      <tr>
        <th>image</th>
        <th>name</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= attachment_image_tag user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size:'40x40' %></td>
          <td><%= user.name %></td>
          <td>フォロー数:<%= user.followings.count %></td>
          <td>フォロワー数:<%= user.followers.count %></td>
          <td><%= link_to "Show", user_path(user), class: "user_#{user.id}" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/index.html.erb
<p id="notice"></p>
<div class="container px-5 px-sm-8">
  <div class="row">
    <%= render 'users/sideBar', users: @users %>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table table-hover table-inverse">

        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <% @users.each do |user| %>
        <tbody>
          <tr>
            <td>
              <%= attachment_image_tag user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size:'40x40' %>
            </td>
            <td>
              <%= user.name %>
            </td>

            <td><p>フォロー数:<%= user.followings.count %></p></td>
						<td><p>フォロワー数:<%= user.followers.count %></p></td>

            <td>
							<% if current_user != user %>
								<% if user.followed_by?(current_user) %>
									<p><%= link_to "フォローを外す", user_relationships_path(user.id), method: :delete %></p>
								<% else %>
									<p><%= link_to "フォローする", user_relationships_path(user.id), method: :post %></p>
								<% end %>
							<% end %>
            </td>
            <td>
              <%= link_to "Show", user_path(user) %>
            </td>
          </tr>
        </tbody>
        <% end %>

      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<p id="notice"></p>
<div class="container px-5 px-sm-8">
  <div class="row">

    <div class="col-md-3">

      <h2>User info</h2>
      <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
      <table class="table">
        <tbody>
          <tr>
            <th>name</th>
            <th><%= @user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= @user.introduction %></th>
          </tr>
          <tr>
            <th>follows</th>
            <th><%= link_to @user.followings.count, users_follow_path(@user) %></th>
          </tr>
          <tr>
            <th>followers</th>
            <th><%= link_to @user.followers.count, users_follower_path(@user) %></th>
          </tr>
        </tbody>
      </table>

			<% if current_user != @user %>
				<% if @user.followed_by?(current_user) %>
					<%= link_to "フォローを外す", user_relationships_path(@user.id), method: :delete, class: 'btn btn-info' %>
				<% else %>
					<%= link_to "フォローする", user_relationships_path(@user.id), method: :post, class: 'btn btn-success'%>
				<% end %>
			<% end %>

      <% if current_user == @user %>
        <div class="row">
          <%= link_to '', edit_user_path(@user.id), class: 'btn btn-outline-secondary btn-block fas fa-user-cog' %>
        </div>
      <% end %>

      <h2 class="mt-3 new_book_">New book</h2>

      <%= form_with model: @book, local:true do |f| %>

        <h4 class="book_title">Title</h4>
        <%= f.text_area :title, size: "20x1" %>
        <h4 class="book_body">Opinion</h4>
        <%= f.text_area :body, size: "20x3" %>
        <div class="form-group">
          <%= f.submit 'Create Book', class: 'btn btn-sm btn-success opinion_field' %>
        </div>
      <% end %>

    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">

        <thead>
          <tr>
            <th>Title</th>
            <th>Body</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <% @books.each do |book| %>
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(@user.id) do %>
                <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size:'40x40' %>
              <% end %>
            </td>
            <td>
              <%= link_to book_path(book.id) do %>
                <%= book.title %>
              <% end %>
            </td>
            <td><%= book.body %></td>

            <td>
              <% if book.favorited_by?(current_user) %>
                <p>
                  <%= link_to book_favorites_path(book), method: :delete do %>
                    ♥<%= book.favorites.count %>
                  <% end %>
                </p>
                <% else %>
                <p>
                  <%= link_to book_favorites_path(book), method: :post do %>
                    ♡<%= book.favorites.count %>
                  <% end %>
                </p>
              <% end %>
            </td>
            <td><%= link_to "comments：#{book.book_comments.count}", book_path(book.id) %></td>

          </tr>
        </tbody>
        <% end %>

      </table>
    </div>
  </div>
</div>